=== CERT-Polska/phobos-cuda-decryptor-poc/config.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Config",
    "definitions": {
        "Config": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "pid": {
                    "type": "integer"
                },
                "tid": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "gettickcount": {
                    "$ref": "#/definitions/Range"
                },
                "filetime": {
                    "$ref": "#/definitions/Range"
                },
                "perfcounter": {
                    "$ref": "#/definitions/Range"
                }
            },
            "required": [
                "filetime",
                "gettickcount",
                "perfcounter",
                "pid",
                "tid"
            ],
            "title": "Config"
        },
        "Range": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "min": {
                    "type": "number"
                },
                "max": {
                    "type": "number"
                },
                "step": {
                    "type": "integer"
                }
            },
            "required": [
                "max",
                "min"
            ],
            "title": "Range"
        }
    }
}

=== CERT-Polska/phobos-cuda-decryptor-poc/sample_data/config.json
{
    "pid": 3152,
    "tid": [
        1492
    ],
    "gettickcount": {
        "min": 1906437,
        "max": 1910437,
        "step": 1
    },
    "filetime": {
        "min": 132489479687980000,
        "max": 132489479688000000,
        "step": 10000
    },
    "perfcounter": {
        "min": 19084704950,
        "max": 19084705150,
        "step": 1
    }
}
